# Generated by Django 2.1.3 on 2018-11-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto_def', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dependencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='lista_registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizado', models.DateField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=1000)),
                ('concepto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.concepto')),
                ('dependencia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.dependencia')),
            ],
        ),
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='lista_registro',
            name='pago_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='registro.pago'),
        ),
        migrations.AddField(
            model_name='lista_registro',
            name='personal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.personal'),
        ),
    ]
