# Generated by Django 2.1.3 on 2018-11-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista_registro',
            name='concepto_id',
        ),
        migrations.RemoveField(
            model_name='lista_registro',
            name='dependencia_id',
        ),
        migrations.RemoveField(
            model_name='lista_registro',
            name='pago_id',
        ),
        migrations.RemoveField(
            model_name='lista_registro',
            name='personal_id',
        ),
        migrations.DeleteModel(
            name='lista_registro',
        ),
    ]
