# Generated by Django 2.1.3 on 2018-11-14 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20181114_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='lista_registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizado', models.DateField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=1000)),
                ('monto', models.CharField(max_length=100)),
                ('concepto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.concepto')),
                ('dependencia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.dependencia')),
                ('pago_id', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='registro.pago')),
                ('personal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.personal')),
            ],
        ),
    ]
