# Generated by Django 2.1.3 on 2018-11-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_lista_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_registro',
            name='fecha_realizado',
            field=models.DateField(default='', null=True),
        ),
    ]
