# Generated by Django 2.1.3 on 2018-11-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20181122_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_registro',
            name='fecha_realizado',
            field=models.DateField(null=True),
        ),
    ]
