# Generated by Django 2.1.3 on 2018-11-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20181122_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_registro',
            name='fecha_realizado',
            field=models.DateField(),
        ),
    ]
