# Generated by Django 2.1.3 on 2018-11-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_auto_20181122_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_registro',
            name='fecha_realizado',
            field=models.DateField(blank=True, default='2018-11-15', null=True),
        ),
    ]
