# Generated by Django 2.1.3 on 2018-11-29 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0011_recibo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recibo',
        ),
    ]
